"""  Local (Web UI) Adapter - 内置 Web 界面适配器 """
import asyncio
import json
import uuid
from datetime import datetime
from typing import Any
from .adapter import (    ChannelAdapter, ChannelType, ChannelConfig,    Message, User, OutgoingMessage, MessageType)  class LocalAdapter(ChannelAdapter):    """本地 Web UI 适配器"""    
    def __init__(self, config: ChannelConfig):        self.config = config        self._users: dict[str, User] = {}        self._sessions: dict[str, str] = {}  # session_id -> user_id        self._message_queues: dict[str, asyncio.Queue] = {}  # user_id -> message queue        
    @property    def channel_type(self) -> ChannelType:        return ChannelType.LOCAL    
    async def initialize(self, config: ChannelConfig) -> bool:        """初始化"""        return True    
    async def send_message(self, user_id: str, message: OutgoingMessage) -> str | None:        """发送消息到 Web 客户端"""        # 检查用户是否在线        if user_id in self._message_queues:            # 添加到用户的消息队列            msg_data = {                "id": str(uuid.uuid4()),                "content": message.content,                "type": message.message_type.value,                "timestamp": datetime.now().isoformat(),            }            await self._message_queues[user_id].put(msg_data)            return msg_data["id"]                return None    
    async def send_ message_by_conversation(self, conversation_id: str, message: OutgoingMessage) -> str | None:        """发送消息到会话"""        return await self.send_message(conversation_id, message)    
    async def handle_webhook(self, payload: dict) -> Message | None:        """处理 Web 消息 - 通过 HTTP 轮询或 WebSocket"""        # Web 消息通过 connect_user / receive_message 处理        return None    
    # =================== Web UI 专用方法 ===================    
    async def connect_user(        self,        user_id: str,        user_name: str = "",    ) -> str:        """        用户连接 Web UI        返回: session_id        """        if user_id not in self._message_queues:            self._message_queues[user_id] = asyncio.Queue()                # 创建用户        if user_id not in self._users:            self._users[user_id] = User(                id=user_id,                name=user_name or f"User_{user_id[:8]}",                platform="local",            )                # 创建会话        session_id = str(uuid.uuid4())        self._sessions[session_id] = user_id                return session_id    
    async def disconnect_user(self, session_id: str):        """用户断开连接"""        if session_id in self._sessions:            user_id = self._sessions.pop(session_id)            # 保留消息队列，等待重连    
    async def receive_message(        self,        session_id: str,        content: str,    ) -> Message | None:        """        接收用户消息        """        if session_id not in self._sessions:            return None                user_id = self._sessions[session_id]        user = self._users.get(user_id)                if not user:            return None                message = Message(            id=str(uuid.uuid4()),            channel="local",            user=user,            content=content,            message_type=MessageType.TEXT,            timestamp=datetime.now(),        )                return message
    
    async def get_user_messages(        self,        user_id: str,        timeout: float = 30.0,    ) -> list[dict]:        """        获取用户消息队列中的消息（Web 轮询用）        """        messages = []                if user_id not in self._message_queues:            return messages                queue = self._message_queues[user_id]                # 尝试获取消息，最多等待        try:            while True:                try:                    msg = await asyncio.wait_for(                        queue.get(),                        timeout=1.0  # 每次等待1秒                    )                    messages.append(msg)                except asyncio.TimeoutError:                    break        except Exception:            pass                return messages    
    async def send_to_all(self, message: OutgoingMessage) -> int:        """        广播消息到所有在线用户        """        count = 0        for user_id in self._message_queues.keys():            result = await self.send_message(user_id, message)            if result:                count += 1        return count
    
    def get_online_users(self) -> list[dict]:        """获取在线用户列表"""        return [            {                "id": user_id,                "name": user.name,                "connected_at": datetime.now().isoformat(),            }            for user_id, user in self._users.items()            if user_id in self._message_queues        ]    
    def supports_buttons(self) -> bool:        return True        def supports_cards(self) -> bool:        return True    
    async def close(self):        """关闭"""        for queue in self._message_queues.values():            queue.put_nowait(None)  # 发送结束信号        self._message_queues.clear()        self._sessions.clear()        self._users.clear()  # =================== Web 消息处理器 ===================  class WebMessageHandler:    """Web 消息处理器 - 用于 FastAPI/WebSocket 集成"""        def __init__(self, adapter: LocalAdapter):        self.adapter = adapter    
    async def on_connect(self, websocket, user_id: str, user_name: str = "") -> str:        """WebSocket 连接时调用"""        return await self.adapter.connect_user(user_id, user_name)    
    async def on_disconnect(self, websocket, session_id: str):        """WebSocket 断开时调用"""        await self.adapter.disconnect_user(session_id)    
    async def on_message(        self,        websocket,        session_id: str,        data: dict,    ) -> Message | None:        """处理收到的 WebSocket 消息"""        msg_type = data.get("type")                if msg_type == "message":            content = data.get("content", "")            return await self.adapter.receive_message(session_id, content)                elif msg_type == "ping":            # 心跳            await websocket.send_json({"type": "pong"})            return None                return None    
    async def send_messages_to_websocket(        self,        websocket,        user_id: str,    ):        """        持续发送消息到 WebSocket        """        while True:            messages = await self.adapter.get_user_messages(user_id, timeout=5.0)                        for msg in messages:                await websocket.send_json({                    "type": "message",                    **msg                })                        # 等待一小段时间            await asyncio.sleep(0.5)